name: slide_puzzle_game
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  image: ^3.1.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  fonts:
    - family: Space-Mode
      fonts:
        - asset: fonts/space-mode-1.0-regular.otf
        - asset: fonts/space-mode-1.0-semibold.otf
          weight: 600
        - asset: fonts/space-mode-1.0-bold.otf
          weight: 700
        - asset: fonts/space-mode-1.0-black.otf
          weight: 800  
  uses-material-design: true
  generate: true
  assets:
   - assets/
   - assets/img/backgrounds/
   - assets/img/characters/
   - assets/img/tiles/uan/
   - assets/img/tiles/inky/
   - assets/img/tiles/ubbi/
   - assets/img/tiles/flamfy/
